name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-release:

    runs-on: ubuntu-latest
    needs: [build-macos]

    steps:
      - uses: actions/checkout@v2
      - id: release
        name: Create Release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
          tag_prefix: v
      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: uploads   
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./uploads/mndyinstaller
          asset_name: mndyinstaller
          tag: ${{ steps.release.outputs.tag_name }}
          overwrite: true
          body: "Monday.com installer"

  build-macos:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org/
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: upload macos artifact
        uses: actions/upload-artifact@v1
        with:
          name: uploads
          path: ./bin/mndyinstaller
